pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'us-east-1'
    }
    stages {
        stage('Creating EKS Cluster') {
            steps {
                script {
                    dir("terraform"){
                        sh "terraform destroy --auto-approve"
                        sh "aws s3 ls"
                        // sh "aws s3 ls s3://state-project"
                        // sh "terraform init"
                        // sh "terraform plan"
                        // sh "terraform apply --auto-approve"
                    }
                }
            }
        }
        stage("Deploy to EKS") {
            steps {
                script {
                    dir('k8') {
                        sh "aws eks update-kubeconfig --name basic-EKS-setup"
                        sh "kubectl apply -f nginx-deployment.yaml"
                        sh "kubectl apply -f nginx-service.yaml"
                    }
                }
            }
        }
    }
}
