apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 724109762092.dkr.ecr.us-east-1.amazonaws.com/python_flask:latest
        ports:
        - containerPort: 5000